[versions]
agp = "8.2.2"
kotlin = "1.9.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.8.2"
composeBom = "2024.03.00"
lottieCompose = "6.4.0"
navVersion = "2.7.7"
googleServices = "4.4.1"
androidGmsVersion = "21.0.0"
firebaseBom = "32.8.0"
firebaseAuth = "22.3.1"
hiltCompiler = "2.49"
devtoolsKspVersion = "1.9.0-1.0.13"
hiltNavigationCompose = "1.2.0"
coil = "2.5.0"
materialExtendedIcon = "1.6.1"
datastorePreferences = "1.0.0"
okhttp = "4.12.0"
retrofit = "2.9.0"
paging3 = "3.2.1"
composeRatingbar = "2.1.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
com-google-android-gms = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "androidGmsVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
com-google-dagger = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltCompiler" }
androidx-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
coil-kt-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "materialExtendedIcon" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging3" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging3" }
compose-ratingbar = { module = "com.github.SmartToolFactory:Compose-RatingBar", version.ref = "composeRatingbar" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidHilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltCompiler" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKspVersion" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }